### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by paglias** [adametry/gulp-eslint#117]
Hi,

I have this gulp task:

```
import gulp from 'gulp';
import eslint from 'gulp-eslint';

gulp.task('lint:server', () => {
  // Ignore .coffee files
  return gulp
    .src(['website/src/**/*.js'])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError());
});

gulp.task('lint', ['lint:server']);
```

and whenever I run it on Node 4.2.1, with last gulp version and gulp-eslint 1.0.0 or `gulp-eslint@rc` I get this error:

```
[18:20:59] Using gulpfile ~/dev/habitrpg/habitrpg/gulpfile.js
[18:20:59] Starting 'lint:server'...
/Users/matteo/dev/habitrpg/habitrpg/node_modules/estraverse/estraverse.js:411
                current = candidates.length;
                                    ^

TypeError: Cannot read property 'length' of undefined
    at Controller.traverse (/Users/matteo/dev/habitrpg/habitrpg/node_modules/estraverse/estraverse.js:411:37)
    at EventEmitter.module.exports.api.verify (/Users/matteo/dev/habitrpg/habitrpg/node_modules/eslint/lib/eslint.js:779:24)
    at processText (/Users/matteo/dev/habitrpg/habitrpg/node_modules/eslint/lib/cli-engine.js:225:27)
    at CLIEngine.executeOnText (/Users/matteo/dev/habitrpg/habitrpg/node_modules/eslint/lib/cli-engine.js:745:26)
    at verify (/Users/matteo/dev/habitrpg/habitrpg/node_modules/gulp-eslint/index.js:20:23)
    at Transform._transform (/Users/matteo/dev/habitrpg/habitrpg/node_modules/gulp-eslint/index.js:68:18)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at write (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/matteo/dev/habitrpg/habitrpg/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
matteo@macbook~/dev/habitrpg/habitrpg$
```

**Comment by paglias** [comment]
This is related to https://github.com/estools/estraverse/issues/61, a quick fix is to add `estraverse@^4.1.0` to you dependencies
