### ISSUE TITLE
failOnError does not exit with status code 1

### ISSUE THREAD

**Issue by yavorski** [adametry/gulp-eslint#133]
Hi,
Tests fails under windows 8.

`λ node -v`
`v4.2.1`

```
ypivanov at YPIVANOV in ~/dev/gulp-eslint on master
λ npm t --verbose
npm info it worked if it ends with ok
npm verb cli [ 'c:\\Program Files\\nodejs\\node.exe',
npm verb cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   't',
npm verb cli   '--verbose' ]
npm info using npm@2.14.7
npm info using node@v4.2.1
npm verb run-script [ 'pretest', 'test', 'posttest' ]
npm info pretest gulp-eslint@1.1.1

> gulp-eslint@1.1.1 pretest c:\Users\ypivanov\dev\gulp-eslint
> jscs *.js test/*.js && gulp test

Error: Path *.js was not found.
    at null.<anonymous> (c:\Users\ypivanov\dev\gulp-eslint\node_modules\jscs\lib\checker.js:188:19)
    at Array.<anonymous> (c:\Users\ypivanov\dev\gulp-eslint\node_modules\jscs\node_modules\vow\lib\vow.js:712:39)
    at Immediate.callFns [as _onImmediate] (c:\Users\ypivanov\dev\gulp-eslint\node_modules\jscs\node_modules\vow\lib\vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
npm verb unsafe-perm in lifecycle true
npm info gulp-eslint@1.1.1 Failed to exec pretest script
npm ERR! Test failed.  See above for more details.
npm verb exit [ 1, true ]
```

How ever I am investigating another issue and just wanted to run the tests, to see if everything is fine.

I looked at examples too, but this is not working for me.
I need this to exit with `status code 1`.

```
gulp.task("eslint", function () {
  return gulp.src("./src/js/**/*.js")
    .pipe(eslint({ extends: "eslint:recommended" }))
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
    .pipe(eslint.failOnError())
});

gulp.task('build', ['eslint', 'js']);
```

Any help will be appreciated.
Thanks in advance.

Here is the output from build task: 

```
λ npm run build

> website@0.0.2 build c:\dev\website-com-assets
> gulp build

[17:04:53] Using gulpfile c:\dev\website-com-assets\gulpfile.js
[17:04:53] Starting 'clean'...
[17:04:53] Finished 'clean' after 25 ms
[17:04:53] Starting 'eslint'...
[17:04:53] Starting 'uglify-all'...
[17:04:54]
src\js\js-2.js
  2:13  warning  Strings must use doublequote  quotes

✖ 1 problem (0 errors, 1 warning)

[17:04:54] Finished 'eslint' after 403 ms
[17:04:54] Finished 'uglify-all' after 397 ms
[17:04:54] Starting 'js'...
[17:04:54] Finished 'js' after 13 μs
[17:04:54] Starting 'build'...
[17:04:54] Finished 'build' after 6.74 μs

> website@0.0.2 postbuild c:\dev\website-com-assets
> npm run revision


> website@0.0.2 revision c:\dev\website-com-assets
> revision ./build/

Revision complete!
```

**Comment by yavorski** [comment]
Hm... my bad, sorry, it fails on `error`.

But is it possible to make it exit with status code 1 when there is a `warning`?

**Comment by adametry** [comment]
Yes. If a task's returned stream emits an error, Gulp will exit the process with status code 1. Using the `result` and `results` methods, you can create any custom failure condition. Here's a condition that fails on the first ESLint result containing any errors or warnings:

```javascript
gulp.task('strict-lint', function() {
	return gulp.src('./src/js/**/*.js')
		.pipe(eslint())
		.pipe(eslint.formatEach())
		.pipe(eslint.result(function(result) {
			// Fail on the first file containing errors or warnings.
			if (result.warningCount > 0 || result.errorCount > 0) {
				// While anything can be thrown to fail the stream,
				// the following properties will influence the resulting Gulp message.
				throw {
					plugin: 'CustomPluginName',
					name: 'CustomErrorType',
					fileName: result.filePath,
					message: error.message,
					lineNumber: error.line,
					showStack: false
				};
			}
		}));
});
```

You can find alternate examples in [example/result.js](https://github.com/adametry/gulp-eslint/blob/master/example/result.js).

On a side note, the example task you provided doesn't need both `failOnError` and `failAfterError` since both will fail a stream containing an ESLint error. The primary difference is *when* they fail the stream.

**Comment by yavorski** [comment]
Hi, I found on `eslint.result` method too and did the job very well.
Thanks very mych.
This is the final result

```
gulp.task("eslint", function() {
  return gulp.src("./src/js/**/*.js")
    .pipe(eslint({ extends: "eslint:recommended" }))
    .pipe(eslint.results(results => results.warningCount ? notify("eslint warning") : util.noop()))
    .pipe(eslint.format())
    .pipe(eslint.failOnError())
    .on("error", onError)
});
```
