### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by unlight** [adametry/gulp-eslint#14]
Node v.11.13, gulp-eslint 0.1.8
```js
	var conf = {
		// rulesdir         : "custom-rules/",
		rules: {
    		"no-use-before-define": [0, "nofunc"],
    		"curly": 1,
    		"no-comma-dangle": 1,
    		"no-debugger": 1,
    		"eol-last": 0,
    		"new-cap": 1,
		},
		globals: {
			// "jQuery": false,
			// "$": true
		},
		env: {
			browser: true,
			node: true
		}
	};
```

```js
	gulp.src(["./src/**.js", "!./src/classList.js"])
		// .pipe(plugins.plumber())
		.pipe(eslint(conf))
		// .pipe(eslint.failOnError())
		.pipe(eslint.formatEach("stylish", process.stdout));
```

    stream.js
          throw er; // Unhandled stream error in pipe.
                ^
    TypeError: Cannot read property 'range' of null
        at EventEmitter.module.exports.api.getTokenBefore (\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:837:31)
        at RuleContext.(anonymous function) [as getTokenBefore] (\node_modules\gulp-eslint\node_modules\eslint\lib\rule-context.js:69:33)
        at checkList (\node_modules\gulp-eslint\node_modules\eslint\lib\rules\no-multi-spaces.js:141:36)
        at EventEmitter.ArrayExpression (\node_modules\gulp-eslint\node_modules\eslint\lib\rules\no-multi-spaces.js:163:13)
        at EventEmitter.emit (events.js:129:20)
        at Controller.controller.traverse.enter (\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:634:25)
        at Controller.__execute (\node_modules\gulp-eslint\node_modules\eslint\node_modules\estraverse\estraverse.js:318:31)
        at Controller.traverse (\node_modules\gulp-eslint\node_modules\eslint\node_modules\estraverse\estraverse.js:394:28)
        at EventEmitter.module.exports.api.verify (\node_modules\gulp-eslint\node_modules\eslint\lib\eslint.js:627:24)
        at verify (\node_modules\gulp-eslint\index.js:22:32)
        at \node_modules\gulp-eslint\index.js:40:18

**Comment by adametry** [comment]
This issue should be resolved with commit 097dfdc43ed50550d97a6c775f003a2e513d2ca5
