### ISSUE TITLE
Cannot set property 'stringify' of undefined

### ISSUE THREAD

**Issue by allyalves** [adametry/gulp-eslint#166]
Ok,

Context: Running gulp-eslint was running fine like last week with babel. Today, I started to work on a new branch and ran the following code to install the dependencies
```
npm install

```
Next, I ran, as usual, a custom command for es-lint which later I tested with another simple code provided by the guidelines on the githubpage
```
gulp.task('lint', () => {
	// ESLint ignores files with "node_modules" paths.
	// So, it's best to have gulp ignore the directory as well.
	// Also, Be sure to return the stream from the task;
	// Otherwise, the task may end before the stream has finished.
	return gulp.src(['**/*.js','!node_modules/**'])
	// eslint() attaches the lint output to the "eslint" property
	// of the file object so it can be used by other modules.
		.pipe(eslint())
		// eslint.format() outputs the lint results to the console.
		// Alternatively use eslint.formatEach() (see Docs).
		.pipe(eslint.format())
		// To have the process exit with an error code (1) on
		// lint error, return the stream and pipe to failAfterError last.
		.pipe(eslint.failAfterError());
});
```

The error was the same as can been seen below:

```
 at loader (/****/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/****/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (utils.js:3:20)
    at Module._compile (module.js:413:34)
```

Any ideas? 
Thanks in advance.

**Comment by shinnn** [comment]
http://www.catb.org/esr/faqs/smart-questions.html#forum
