### ISSUE TITLE
"error incorrect header  header/header" on first char of every file in project

### ISSUE THREAD

**Issue by rmhines** [adametry/gulp-eslint#176]
I'm the only Windows user out of a team of Mac users, but we're all running our application inside a Vagrant VM. I believe this is a BOM, newline, or other character encoding issue relating to the project files as they exist on my host operating system. For now my only workaround has been disabling eslint.failAfterError() during the gulp lint task, and having to manually scan over the 246 "incorrect header  header/header" errors to check for any real linting errors. 

```
[19:28:53] Finished 'build:version-file' after 52 s
[19:28:53] Starting 'lint'...
[19:29:05] Starting 'assets'...
[19:30:08]
/home/vagrant/ibe-editor2/src/app.js
  19:1  error  incorrect header  header/header

/home/vagrant/ibe-editor2/src/isomorphic.js
  18:1  error  incorrect header  header/header
```
[More errors for each file in the project directory]
```
/home/vagrant/ibe-editor2/gulpfile.js
  20:1  error  incorrect header  header/header

✖ 246 problems (246 errors, 0 warnings)

[19:30:08] 'lint' errored after 1.25 min
[19:30:08] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 246 errors
[19:30:09] 'test:unit' errored after 2.12 min
[19:30:09] Error: [object Object]
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/vagrant/ibe-editor2/node_modules/orchestrator/index.js:264:8)
    at /home/vagrant/ibe-editor2/node_modules/orchestrator/index.js:275:23
    at finish (/home/vagrant/ibe-editor2/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/vagrant/ibe-editor2/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/home/vagrant/ibe-editor2/node_modules/run-sequence/index.js:53:5)
    at Gulp.onError (/home/vagrant/ibe-editor2/node_modules/run-sequence/index.js:60:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/vagrant/ibe-editor2/node_modules/orchestrator/index.js:264:8)
    at /home/vagrant/ibe-editor2/node_modules/orchestrator/index.js:275:23
    at finish (/home/vagrant/ibe-editor2/node_modules/orchestrator/lib/runTask.js:21:8)
    at Transform.<anonymous> (/home/vagrant/ibe-editor2/node_modules/orchestrator/lib/runTask.js:52:4)
[19:30:20] 'assets' all files 0 B
[19:30:20] Finished 'assets' after 1.25 min
```

**Comment by shinnn** [comment]
https://github.com/adametry/gulp-eslint/issues/173#issuecomment-242888359

**Comment by junaidahmed501** [comment]
> 
> 
> [Not a gulp-eslint issue](http://www.catb.org/esr/faqs/smart-questions.html#forum). Those errors seem to be emitted by [eslint-plugin-header](https://github.com/Stuk/eslint-plugin-header).

Yup, that's correct. I had to look into `eslintrc.json` in my Angular project to finally be able to resolve the issue.
Actually, I just ran my `lint` command with `--fix` which did the trick with me manually changing things.
