### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by boardgames** [adametry/gulp-eslint#190]
Ubuntu

nodejs -v
v6.9.4

npm -v
3.10.10

node_modules/gulp-eslint/index.js:3
const BufferStreams = require('bufferstreams');
^^^^^
SyntaxError: Use of const in strict mode.
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/home/bitnami/mobicon/app/controllers/projects/projects.lint.server.controller.js:8:14)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/home/bitnami/mobicon/app/controllers/projects.server.controller.js:15:3)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/home/bitnami/mobicon/app/routes/projects.server.routes.js:7:14)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)

Any idea?

**Comment by shinnn** [comment]
Add `console.log(process.version);` to the top of your `gulpfile.js` and you can confirm that you're running gulp.js with older Node.js.
