### ISSUE TITLE
getting an error - 

### ISSUE THREAD

**Issue by GuyMograbi** [adametry/gulp-eslint#199]
Getting this error. 

All I am doing is `npm install` and run the gulp task. 

Any idea how I can resolve this?

```
~/node_modules/eslint/lib/token-store/utils.js:41
    return lodash.sortedIndexBy(
                  ^

TypeError: lodash.sortedIndexBy is not a function
    at Object.search (~/node_modules/eslint/lib/token-store/utils.js:41:19)
    at new BackwardTokenCommentCursor (~/node_modules/eslint/lib/token-store/backward-token-comment-cursor.js:36:35)
    at CursorFactory.createBaseCursor (~/node_modules/eslint/lib/token-store/cursors.js:53:16)
    at CursorFactory.createCursor (~/node_modules/eslint/lib/token-store/cursors.js:71:27)
    at createCursorWithSkip (~/node_modules/eslint/lib/token-store/index.js:114:20)
    at TokenStore.getTokenBefore (~/node_modules/eslint/lib/token-store/index.js:312:16)
    at report (~/node_modules/eslint/lib/rules/key-spacing.js:416:47)
    at verifySpacing (~/node_modules/eslint/lib/rules/key-spacing.js:593:17)
    at EventEmitter.Property (~/node_modules/eslint/lib/rules/key-spacing.js:632:17)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector (~/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (~/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (~/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (~/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (~/node_modules/eslint/lib/util/comment-event-generator.js:98:23)

```

**Comment by adametry** [comment]
Your error doesn't appear to involve the `gulp-eslint` package.

You should verify your installed version of `lodash` and check with `eslint` [issues](https://github.com/eslint/eslint/issues).
