### ISSUE TITLE
Combined with simple eslint-starter, gulp-eslint generates error

### ISSUE THREAD

**Issue by BurtHarris** [adametry/gulp-eslint#202]
I've tried applying gulp-eslint to the spicydonuts/eslint-starter project.   When run from gulp, it now generates this message:

```
C:\code\eslint-starter>gulp
[10:30:30] Using gulpfile C:\code\eslint-starter\gulpfile.js
[10:30:30] Starting 'lint'...

events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: [object Object]:
        ESLint configuration is invalid:
        - Unexpected top-level property "ecmaFeatures".

Referenced from: C:\code\eslint-starter\.eslintrc
    at validateConfigSchema (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:192:15)
    at Object.validate (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:205:5)
    at loadFromDisk (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:549:19)
    at load (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:592:20)
    at configExtends.reduceRight (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:405:28)
    at loadFromDisk (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:556:22)
    at Object.load (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:592:20)
    at Config.getLocalConfigHierarchy (C:\code\eslint-starter\node_modules\gulp-eslint\node_modules\eslint\lib\config.js:228:44)
```

Repro case in __gulp-eslint__ branch here:  https://github.com/BurtHarris/eslint-starter/tree/gulp-eslint

I originally thought this was due to the YAML syntax in __.eslintrc__ ( spicydonuts/eslint-starter#1) , but further exploration left me thinking its a problem with the __gulp-eslint__ plugin.   Running __eslint__ directly works OK.

**Comment by BurtHarris** [comment]
My error, looks like this was due to a configuration file in my home directory.
