### ISSUE TITLE
gulp-eslint cannot resolve extends "plugin:react/recommended"

### ISSUE THREAD

**Issue by mrducnguyen** [adametry/gulp-eslint#205]
Hi,

I'm having a very frustrated issue and haven't been able to fix it.

I'm using Gulp, Eslint and React, with Babel, so I install eslint-plugin-react, below is my `.eslintrc` file:

```json
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "extends": [
      "eslint:recommended", 
      "plugin:react/recommended"
  ]
}
```

And below is my `lint` task

```javascript
gulp.task('lint', () =>
  gulp.src(['app/scripts/**/*.js','!node_modules/**'])
    .pipe($.eslint())
    .pipe($.eslint.format())
);
```

I install both `eslint` and `eslint-plugin-react` locally, and I can run `eslint` locally without any problem using local command: `./node_modules/.bin/eslint [scripts_foder]`

But whenever I try `gulp lint` I get this error message:
```log
[app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-plugin:react/recommended
Error: Cannot find module 'eslint-config-plugin:react/recommended'
Referenced from: [app_folder]\.eslintrc
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at loadPackage ([app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:168:16)
    at loadConfigFile ([app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:212:18)
    at load ([app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:385:18)
    at [app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends ([app_folder]\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:309:28)
```

I tried to comprehend what happened (coming from a Java Backend dev), I think it's something related to Absolute and/or Relative path resolving issue there, as the exception was thrown here `gulp-eslint\node_modules\eslint\lib\config\config-file.js:332`  

I'm currently falling back using `gulp-run` to call `eslint` command directly, but that's counter-intuitive and I won't be able to stop the build without complex code to check command result...

Any suggestions for me?

Thanks,

**Comment by shinnn** [comment]
> gulp-eslint cannot resolve extends "plugin:react/recommended"

No.

`eslintrc.js`

```js
module.exports = {
  parser: 'babel-eslint',
  plugins: [
    'react'
  ],
  extends: [
    'eslint:recommended', 
    'plugin:react/recommended'
  ]
};
```

`sample.js`

```js
'use strict';

const {join} = require('path');

const gulpEslint = require('gulp-eslint');
const File = require('vinyl');

gulpEslint()
.on('finish', () => console.log('No error.'))
.end(new File({
  path: join(__dirname, 'fixture.js'),
  content: Buffer.from('console.log(\'Hi.\');\n')
}));
```

```
$ node sample.js
> No error.
```
