### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by shouryamittal** [adametry/gulp-eslint#258]
Hi,
I'm using gulp-eslint 6.0.0, with the following other tools:
node: 10.15.3
npm: 6.4.1
gulp-cli: 2.2.0

**Upon execution, I'm getting the following error:**

 ...calculateStatsPerFile(messages)
        ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)

**Following is my eslintrc file:**

`{
    "env": {
        "node": true,
        "es6": true
    },
    "parserOptions": {
        "ecmaVersion":2020,
        "ecmaFeatures": {
            "jsx": true
        }
    },
    "settings": {
        "react": {
          "createClass": "createClass",
          "pragma": "React",
          "version": "detect"
        }
    },
    //this config extends the eslint recommended and react presets.
    "extends":["eslint:recommended", "plugin:react/recommended"],
    //rules to be applied by eslint while validating the code.
    "rules": {
        "curly": "error", //enforce consistent brace style for all control statements
        "no-undef": "error", //disallow the use of undeclared variables unless mentioned in `/*global */` comments
        "no-unused-vars": "error",
        "no-trailing-spaces": "error",
        "semi": "error", //semicolons a must to end a statement
        "no-const-assign": "error",
        "eqeqeq": "error", //require the use of `===` and `!==`
        "no-extra-boolean-cast":"off"
    }
}`

Any help is appreciated, Thanks.

**Comment by doamatto** [comment]
Can you try using the latest version of my fork to see if that fixes your problem? I don't believe this repo is being maintained anymore, but I'll try to fix your issue on that repo if it persists

Repo: https://github.com/doamatto/gulp-eslint

Cheers!
- Matt

**Comment by shouryamittal** [comment]
Hi Matt,

Even after using https://github.com/doamatto/gulp-eslint, the errors
persist.
Can you pls look into this?

Thanks,
Shourya

**Comment by doamatto** [comment]
Sorry for taking so long to respond. I've made an issue in my repository (doamatto/gulp-eslint#65) that I'm going to use to solve this. Please read the updates there :)
