### ISSUE TITLE
Fails when parser is babel-eslint and using ES6 import syntax

### ISSUE THREAD

**Issue by kentor** [adametry/gulp-eslint#38]
package.json:
```json
{
  "name": "eslint-test",
  "version": "0.0.0",
  "devDependencies": {
    "babel-eslint": "^1.0.12",
    "eslint": "^0.15.1",
    "gulp": "^3.8.11",
    "gulp-eslint": "^0.5.0"
  }
}
```

.eslintrc:
```yaml
---
parser: babel-eslint
```

gulpfile.js:
```javascript
ar gulp = require('gulp');
var eslint = require('gulp-eslint');

gulp.task('lint', function() {
  gulp.src(['index.js'])
    .pipe(eslint())
    .pipe(eslint.format());
});

gulp.task('default', ['lint']);
```

index.js:
```javascript
import gulp from 'gulp';
```

Using the eslint binary works as expected:
```bash
$ ./node_modules/.bin/eslint index.js

index.js
  1:7   error  gulp is defined but never used  no-unused-vars
  1:17  error  Strings must use doublequote    quotes

✖ 2 problems (2 errors, 0 warnings)
```

But using gulp task blows up:
```shell
$ gulp
[11:57:41] Using gulpfile ~/stuff/eslint-test/gulpfile.js
[11:57:41] Starting 'lint'...
[11:57:41] Finished 'lint' after 14 ms
[11:57:41] Starting 'default'...
[11:57:41] Finished 'default' after 12 μs

/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/escope.js:73
            throw new Error(text);
                  ^
Error
    at assert (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/escope.js:73:19)
    at Referencer.extend.ImportDeclaration (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/escope.js:1348:13)
    at Referencer.Visitor.visit (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Referencer.Visitor.visitChildren (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:88:38)
    at Referencer.extend.Program (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/escope.js:1201:18)
    at Referencer.Visitor.visit (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/node_modules/esrecurse/esrecurse.js:109:34)
    at Object.analyze (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/node_modules/escope/escope.js:1392:20)
    at EventEmitter.module.exports.api.verify (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:623:35)
    at verify (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/Users/kentor/stuff/eslint-test/node_modules/gulp-eslint/index.js:44:18)
```

**Comment by shinnn** [comment]
Did you set `parser` config as documented?

https://github.com/babel/babel-eslint#setup

**Comment by kentor** [comment]
Yep, let me put the .eslintrc file in the OP. Using the eslint in ./node_modules/.bin directly works so I'm sure it's using the babel-eslint parser correctly.

**Comment by shinnn** [comment]
@kentor Could you show us your .eslintrc?

**Comment by kentor** [comment]
```yaml
---
parser: babel-eslint
```

**Comment by shinnn** [comment]
Hmm, I created exactly the same files and ran `gulp`, but it works well.

```sh
[06:00:54] Using gulpfile ~/github/eslint-test/gulpfile.js
[06:00:54] Starting 'lint'...
[06:00:54] Finished 'lint' after 16 ms
[06:00:54] Starting 'default'...
[06:00:54] Finished 'default' after 9.47 μs
```

* Which version of Node are you using? (Currently I'm using io.js v1.3.0.)
* Could you re-install all the dependencies and try it again?

**Comment by kentor** [comment]
Oh hmm, I removed my `node_modules` directory and ran `npm install` and it works now. Thanks for looking into this.

**Comment by spicydonuts** [comment]
I had the same problem.  `rm -rf node_modules && npm i` also fixed it for me.  Never seen that problem before so it may be one of the dependencies.. kinda weird.

**Comment by jaredly** [comment]
for me `npm install -U -g babel-eslint` fixed it
