### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by PascalPrecht** [adametry/gulp-eslint#83]
```
$ gulp eslint
[10:42:55] Using gulpfile ~/projects/thoughtram/sample-app/gulpFile.js
[10:42:55] Starting 'eslint'...
[10:42:55] 'eslint' errored after 5.93 ms
[10:42:55] TypeError: undefined is not a function
    at DestroyableTransform.Readable.pipe (/Users/pascalprecht/projects/thoughtram/sample-app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/Users/pascalprecht/projects/thoughtram/sample-app/gulpFile.js:28:6)
    at module.exports (/Users/pascalprecht/projects/thoughtram/sample-app/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/pascalprecht/projects/thoughtram/sample-app/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/pascalprecht/projects/thoughtram/sample-app/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/pascalprecht/projects/thoughtram/sample-app/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/pascalprecht/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

Gulpfile.js

```
gulp.task('eslint', function () {
  return gulp.src('src/**/*.js')
    .pipe(eslint, {
      configFile: path.join(__dirname, '.eslintrc')
    });
});
```

Any idea?

**Comment by Tharkun86** [comment]
Looks like a syntax error to me - this should work:

```
gulp.task('eslint', function () {
  return gulp.src('src/**/*.js')
    .pipe(eslint({
      configFile: path.join(__dirname, '.eslintrc')
    }));
});
```

**Comment by PascalPrecht** [comment]
That did the trick! 😖
