### ISSUE TITLE
lastVariableName "memo.id.name" memo is undefined

### ISSUE THREAD

**Issue by gajus** [adametry/gulp-eslint#86]
`"gulp-eslint": "^1.0.0"`

```
curiosity:2015 09 01 showtimes gajus$ gulp lint
[11:22:01] Using gulpfile /foo/gulpfile.js
[11:22:01] Starting 'lint'...
[11:22:02] 'lint' errored after 477 ms
[11:22:02] ESLintError in plugin 'gulp-eslint'
Message:
    Variables within the same declaration block should be sorted alphabetically
Details:
    fileName: /foo/src/app/selector.js
    lineNumber: 6
/foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:21
                    var lastVariableName = memo.id.name,
                                               ^
TypeError: Cannot read property 'id' of undefined
    at /foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:21:48
    at Array.reduce (native)
    at EventEmitter.VariableDeclaration (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:19:31)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:824:25)
    at Controller.__execute (/foo/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/foo/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:817:24)
    at processText (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:199:27)
```

**Comment by gajus** [comment]
This appears to be an issue specific to `gulp-eslint` as opposed to `eslint` package. Running `eslint` CLI tool does not produce the same error:

```
curiosity:foo gajus$ eslint ./src/app/selector.js

./src/app/selector.js
   6:5   error  Variables within the same declaration block should be sorted alphabetically  sort-vars
   6:5   error  Variable 'locationSelector' should not be initialized on declaration         init-declarations
   6:24  error  Expected parentheses around arrow function argument                          arrow-parens
   7:5   error  Variables within the same declaration block should be sorted alphabetically  sort-vars
   7:5   error  Variable 'screeningSelector' should not be initialized on declaration        init-declarations
   7:25  error  Expected parentheses around arrow function argument                          arrow-parens
   8:5   error  Variables within the same declaration block should be sorted alphabetically  sort-vars
  11:5   error  Expected line before comment                                                 lines-around-comment
  21:16  error  "_" is not defined                                                           no-undef
  21:33  error  Expected parentheses around arrow function argument                          arrow-parens
  21:33  error  location is already declared in the upper scope                              no-shadow
  22:17  error  event is already declared in the upper scope                                 no-shadow
  22:17  error  Variable 'event' should not be initialized on declaration                    init-declarations
  25:32  error  "_" is not defined                                                           no-undef
  32:16  error  "_" is not defined                                                           no-undef
  32:31  error  event is already declared in the upper scope                                 no-shadow
  32:31  error  Expected parentheses around arrow function argument                          arrow-parens
  39:5   error  Assignment to function parameter 'state'                                     no-param-reassign

✖ 18 problems (18 errors, 0 warnings)
```

**Comment by adametry** [comment]
So far, I've been unable to reproduce the "Cannot read property 'id' of undefined" error in _gulp-eslint_ or _eslint-watch_. My tests have been built around your example in https://github.com/eslint/eslint/issues/3474#issuecomment-133380490 and by establilshing an .eslintrc + selector.js that results in the example _eslint_ report above. This leads me to believe that there are other variables involved (e.g., .eslintrc, gulpfile.js, package.json). 

One interesting aspect of your _gulp-eslint_ output is that it fails as a result of a linting report (rule sort-vars in selector.js on line 6). I can assume that `failOnError` is responsible for the initial error message, and that the process is exiting when the "Cannot read property 'id' of undefined" error occurred in sort-vars.js. This implies two things:
  1. selector.js linting was completed; otherwise, the lint results would not have arrived at `failOnError` for evaluation.
  2. _eslint_ threw the "Cannot read property 'id' of undefined" exception while processing a subsequent file. It is fairly common to see additional output after `process.exit()` as the process' event stack drains.

So, here are my questions:
  1. Does your gulp "lint" task specific reference "selector.js" or are there other files being linted?
  2. If so, do you see the `sort-vars.js` error if you specifically ignore/skip "selector.js" from gulp (e.g., `gulp.src(['src/**/*.js','!**/selector.js'])`)?
  3. If so, does the eslint cli also produce this error when ignoring "selector.js" (e.g., `eslint ./src --ignore-pattern "**/selector.js"`)?
  4. If any answers to the above questions are "no," could you provide an example repo or other means of demonstrating this error?

**Comment by gajus** [comment]
@adametry You are right as far as it was not "selector.js" that was causing the issue. I have restored the version at the time and am unable to reproduce the error. I will continue development and will report if this error occurs ever again.

**Comment by gajus** [comment]
```js
export default class {
    render () {
        let {
            a
        } = this,
            // Presence of variable declaration after destruction causes the error.
            b;
    }
}
```

Adding this code produces the following error:

```
/foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:21
                    var lastVariableName = memo.id.name,
                                               ^
TypeError: Cannot read property 'id' of undefined
    at /foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:21:48
    at Array.reduce (native)
    at EventEmitter.VariableDeclaration (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/rules/sort-vars.js:19:31)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:824:25)
    at Controller.__execute (/foo/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/foo/node_modules/gulp-eslint/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:817:24)
    at processText (/foo/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine.js:199:27)
```

**Comment by shinnn** [comment]
@gajus A small repository that can reproduce the problem is very welcome, rather than code snippets.

**Comment by gajus** [comment]
This appears to be babel-eslint specific, https://github.com/gajus/eslint-issue-3474.

**Comment by shinnn** [comment]
A small repository that can reproduce the *plugin-specific* problem is very welcome.

**Comment by shinnn** [comment]
OK, seems an issue with babel-eslint.
